// Copyright by Procgen Labs Ltd. All Rights Reserved.

#include "VoxelToHLSL/PGLHLSLDocumentBuilder.h"
#include "VoxelToHLSL/PGLVoxelGraphTraverser.h"
#include "VoxelToHLSL/PGLHLSLHelperLibrary.h"

FString FPGLHLSLDocumentBuilder::Build() const
{
	FString Result;
	Result.Reserve(8192);

	// Header
	Result += BuildHeader();

	// Helper macros (only those actually needed)
	const FString Helpers = BuildHelperFunctions();
	if (!Helpers.IsEmpty())
	{
		Result += TEXT("\n// ============================================================\n");
		Result += TEXT("// Helper Macros (PCG kernels run inside a function body,\n");
		Result += TEXT("// so we use #define macros instead of function definitions)\n");
		Result += TEXT("// ============================================================\n\n");
		Result += Helpers;
	}

	// Main graph logic
	Result += TEXT("\n// ============================================================\n");
	Result += TEXT("// Graph Logic\n");
	Result += TEXT("// ============================================================\n\n");

	for (const FString& Statement : Statements)
	{
		Result += Statement + TEXT("\n");
	}

	// Output writes
	const FString OutputWrites = BuildOutputWrites();
	if (!OutputWrites.IsEmpty())
	{
		Result += TEXT("\n// --- Write Outputs ---\n");
		Result += OutputWrites;
	}

	return Result;
}

FString FPGLHLSLDocumentBuilder::BuildHeader() const
{
	FString Header;

	Header += TEXT("// ============================================================\n");
	Header += FString::Printf(TEXT("// Auto-generated from Voxel Graph: %s\n"), *GraphName);
	Header += TEXT("// Generated by PGL Voxel-to-HLSL Translator\n");
	Header += TEXT("// PCG Kernel Type: PointProcessor\n");
	Header += FString::Printf(TEXT("// Input Pin: \"%s\" | Output Pin: \"%s\"\n"), *InputPinName, *OutputPinName);

	if (Warnings.Num() > 0)
	{
		Header += TEXT("//\n// WARNINGS:\n");
		for (const FString& Warning : Warnings)
		{
			Header += FString::Printf(TEXT("//   - %s\n"), *Warning);
		}
	}

	Header += TEXT("// ============================================================\n");

	// Setup instructions for required input/output attributes
	if (Inputs.Num() > 0 || Outputs.Num() > 0)
	{
		Header += TEXT("//\n");
		Header += TEXT("// REQUIRED PCG NODE SETUP:\n");
		Header += TEXT("//\n");

		if (Inputs.Num() > 0)
		{
			Header += TEXT("// Input attributes (must exist on input points):\n");
			for (const FPGLGraphInput& Input : Inputs)
			{
				Header += FString::Printf(TEXT("//   - \"%s\" (%s)\n"), *Input.Name.ToString(), *Input.HLSLType);
			}
		}

		if (Outputs.Num() > 0)
		{
			Header += TEXT("//\n");
			Header += TEXT("// Output attributes to create (Custom HLSL node > Output Pins >\n");
			Header += TEXT("//   Out > GPU Properties > Attributes to Create):\n");
			for (const FPGLGraphOutput& Output : Outputs)
			{
				Header += FString::Printf(TEXT("//   - \"%s\" (%s)\n"), *Output.Name.ToString(), *Output.HLSLType);
			}
		}

		Header += TEXT("//\n");
		Header += TEXT("// ============================================================\n");
	}

	// PI definition guard
	Header += TEXT("\n#ifndef PI\n");
	Header += TEXT("#define PI 3.14159265358979323846f\n");
	Header += TEXT("#endif\n");

	return Header;
}

FString FPGLHLSLDocumentBuilder::BuildHelperFunctions() const
{
	FString Helpers;

	// Hash macros (needed by noise, random, etc.)
	if (RequiredHelpers.bNeedsHash)
	{
		Helpers += FPGLHLSLHelperLibrary::GetHashMacro();
		Helpers += TEXT("\n");
	}

	// Random
	if (RequiredHelpers.bNeedsRandRange)
	{
		Helpers += FPGLHLSLHelperLibrary::GetRandRangeMacro();
		Helpers += TEXT("\n");
	}

	// Interpolation (expression macros)
	if (RequiredHelpers.bNeedsLerp)
	{
		Helpers += FPGLHLSLHelperLibrary::GetLerpMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsSmoothStep)
	{
		Helpers += FPGLHLSLHelperLibrary::GetSmoothStepMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsBilerp)
	{
		Helpers += FPGLHLSLHelperLibrary::GetBilerpMacro();
		Helpers += TEXT("\n");
	}

	// Noise common macros (fade, grad2, grad3)
	if (RequiredHelpers.HasAnyNoise())
	{
		Helpers += FPGLHLSLHelperLibrary::GetNoiseCommonMacros();
		Helpers += TEXT("\n");
	}

	// Noise function macros
	if (RequiredHelpers.bNeedsPerlin2D)
	{
		Helpers += FPGLHLSLHelperLibrary::GetPerlin2DMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsPerlin3D)
	{
		Helpers += FPGLHLSLHelperLibrary::GetPerlin3DMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsSimplex2D)
	{
		Helpers += FPGLHLSLHelperLibrary::GetSimplex2DMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsSimplex3D)
	{
		Helpers += FPGLHLSLHelperLibrary::GetSimplex3DMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsCellular2D)
	{
		Helpers += FPGLHLSLHelperLibrary::GetCellular2DMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsCellular3D)
	{
		Helpers += FPGLHLSLHelperLibrary::GetCellular3DMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsValue2D)
	{
		Helpers += FPGLHLSLHelperLibrary::GetValue2DMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsValue3D)
	{
		Helpers += FPGLHLSLHelperLibrary::GetValue3DMacro();
		Helpers += TEXT("\n");
	}

	// Quaternion helper macros
	if (RequiredHelpers.bNeedsQuaternionFromEuler)
	{
		Helpers += FPGLHLSLHelperLibrary::GetQuatFromEulerMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsEulerFromQuaternion)
	{
		Helpers += FPGLHLSLHelperLibrary::GetEulerFromQuatMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsQuaternionFromAxis)
	{
		Helpers += FPGLHLSLHelperLibrary::GetQuatFromAxisMacro();
		Helpers += TEXT("\n");
	}

	if (RequiredHelpers.bNeedsDistanceFieldColor)
	{
		Helpers += FPGLHLSLHelperLibrary::GetDistanceFieldColorMacro();
		Helpers += TEXT("\n");
	}

	return Helpers;
}

FString FPGLHLSLDocumentBuilder::BuildOutputWrites() const
{
	FString Result;
	for (const FPGLGraphOutput& Output : Outputs)
	{
		Result += Output.PCGWriteStatement + TEXT("\n");
	}
	return Result;
}
